### ISSUE TITLE
Version mismatched

### ISSUE THREAD

**Issue by favoyang** [jelte/be.khepri.play.assetdelivery.addressables#15]
https://openupm.com/packages/be.khepri.pad-addressables/?subPage=pipelines

Git tag: 1.0.0-rc2
package.json version: [1.0.0-rc1](https://github.com/jelte/be.khepri.play.assetdelivery.addressables/blob/1.0.0-rc2/package.json)

Fix:
- bump version and re-tag 1.0.0-rc2

**Comment by jelte** [comment]
oops, done.
