### ISSUE TITLE
Not all groups were created correctly by Create config for Addressable Groups

### ISSUE THREAD

**Issue by ReSY93** [jelte/be.khepri.play.assetdelivery.addressables#16]
In my project there are 4 groups: Campaign, Background, Preview, and Custom Game. Addressable is used to create the campaign_assets_all.bundle, background_assets_all.bundle, preview_assets_all.bundle, and customgame_assets_all.bundle. The Custom Game bundle is created without the underscore (custom_game). And when I create groups from the menu Google -> Create config for Addressable Groups, 3 directories are created: campaign_assets_all, background_assets_all, preview_assets_all in the \Library\be directory.khepri.play\StreamingAssetsCopy. But the directory for Custom Game is not created.

Apparently, the problem is in the search, in the AssetPackBuilder.GetAssetPackGroupSchema(string bundle) method (.Where(group => Path.GetFileName(bundle).StartsWith(group.Name.ToLower()))). In my case, I changed the name of the Custom Game group to CustomGame (without underscore) in Addressables, and after that all 4 directories were created in \Library\be.khepri.play\StreamingAssetsCopy

Unity 2020.1.4f, Addressables Package 1.16.10, tested on Google Play Asset Delivery - Addressables Version 1.0.0-rc3

**Comment by jelte** [comment]
Seems addressables does some additional filtering, fixed this in 1.0.0-rc4.
