### ISSUE TITLE
Error when Building Asset Packs

### ISSUE THREAD

**Issue by phamhung99** [jelte/be.khepri.play.assetdelivery.addressables#26]
Hi, 
When I building asset packs by the scripted build process, I got an error
![BuildBundleError](https://user-images.githubusercontent.com/43336623/105160009-4f387000-5b42-11eb-9ecd-42be34896727.PNG)

**Comment by jelte** [comment]
can you give a bit more info. ( full stack trace)

I'm guessing the assetPackConfig is null.
