### ISSUE TITLE
Fail to create config for Addressables Groups

### ISSUE THREAD

**Issue by minidragon-jacky** [jelte/be.khepri.play.assetdelivery.addressables#34]
Hello, I just follow the instruction to set up the addressables asset for play asset delivery. Add scheme to all of the addressables groups. Rebuild the addressables assets. And then try to create config for addressables groups. But I get error saying that could no find a part of the path.

![image](https://user-images.githubusercontent.com/67568445/126132491-18dd478f-d567-4532-a420-87d422a6fb4a.png)

The file that showed in the path exists but the path having both slash and backslash. Don't don't whether it is related.
My Unity version is 2019.4.21f1.

**Comment by jelte** [comment]
hm, one thing I know that may be an issue on windows is the length of filepaths.

could you try reducing the name of the bundle? just to see if it works

**Comment by minidragon-jacky** [comment]
Oh, it works after reduces the name length.
I did not check the length of the second path and thought that it will not be used if file exist in the first path.
Reducing the path length to <200 of both paths fixes the issue,
