### ISSUE TITLE
Encounter error when trying to build in batch mode, work fine in Editor

### ISSUE THREAD

**Issue by kure-kung** [jelte/be.khepri.play.assetdelivery.addressables#35]
21:23:52 Khepri.PlayAssetDelivery.Editor.AssetPackBuilder:BuildBundleWithAssetPacks (UnityEditor.BuildPlayerOptions,UnityEditor.MobileTextureSubtarget,string) (at Library/PackageCache/be.khepri.play.assetdelivery.addressables@69dccaaacf/Editor/AssetPackBuilder.cs:76)
21:23:52 Jenkins:BuildForPlatform (string,UnityEditor.BuildTarget,string,string,string,string) (at Assets/Scripts/General/Editor/Jenkins.cs:991)
21:23:52 Jenkins:BuildForPlatformAndroid () (at Assets/Scripts/General/Editor/Jenkins.cs:922)
21:23:52 
21:23:52 (Filename: Library/PackageCache/com.google.android.appbundle@1.2.0/Editor/Scripts/Internal/BuildTools/BuildToolLogger.cs Line: 61)
21:23:52 
21:23:52 Cancelling DisplayDialog: Build Error Build failed with 2 error(s)
21:23:52 This should not be called in batch mode.

**Comment by jelte** [comment]
this gives me no information what so ever.
Could you please add the 2 errors or the entire relevant log ?
