### ISSUE TITLE
Package fails to ignore iOS project

### ISSUE THREAD

**Issue by minidragon-jacky** [jelte/be.khepri.play.assetdelivery.addressables#36]
Hello.

I have an Unity project for both Android and iOS. The package tries to run the code even if I build addressable asset in iOS platform. But Google hides the code when the platform is not in Android. The package failed to run and thus addressable asset cannot be built.

![image](https://user-images.githubusercontent.com/67568445/126601040-c9764b8a-d0cc-4502-b000-21a28fe8e13e.png)

Is there any solution rather than comment out the scripts one by one in my iOS side project?

**Comment by jelte** [comment]
This was actually already been resolved by #24 , I just have been not really been paying attention to this package as I don't really use it at the moment. Sorry.

I've merge the PR and should be working now in rc5.
