### ISSUE TITLE
error AssetPackBuilder.cs api

### ISSUE THREAD

**Issue by yingnierxiao** [jelte/be.khepri.play.assetdelivery.addressables#37]
version google  https://github.com/google/play-unity-plugins/releases

Library/PackageCache/be.khepri.play.assetdelivery.addressables@84b86cc9db/Editor/AssetPackBuilder.cs(105,33): error CS7036: There is no argument given that corresponds to the required formal parameter 'forceSynchronousBuild' of 'AppBundlePublisher.Build(BuildPlayerOptions, AssetPackConfig, bool)'

**Comment by jelte** [comment]
Seems to API of google has changed and they didn't bother to respect backwards compatiblity...
it was changed in 1.5, so 1.4.0 should work. 

(not sure when I'll have time myself to upgrade to 1.5 and implement the change, it's not much work but need to find time :))

**Comment by SinTrace** [comment]
Has this problem been resolved?

**Comment by jelte** [comment]
This is fixed in version 1.0.0.
