### ISSUE TITLE
android runtime assetbundle path error

### ISSUE THREAD

**Issue by Jason-Zy** [jelte/be.khepri.play.assetdelivery.addressables#38]
![image](https://user-images.githubusercontent.com/26757867/129567850-67922390-52ed-4e5c-918d-c4c5985961ab.png)
i build my aab and use bundletool to install the app on my simulator, it seems to find the bundle in the base.apk while i know that the bundle should be in the split asset apk. whats wrong with that? any suggestion?

**Comment by jelte** [comment]
Hi,
I don't think Play.AssetDelivery will work without using the play store. As the asset bundles are not added to the Play AssetDelivery service.

I think to only way to test it is to actually use the playstore. You can use the internal track or internal builds feature there to test things. It's a pain, but I think that's the only way.

You should also check with the debugger that the app calls the 
https://github.com/jelte/be.khepri.play.assetdelivery.addressables/blob/master/Runtime/ResourceHandlers/AssetPackAssetBundleResourceHandlerBase.cs#L12 and https://github.com/jelte/be.khepri.play.assetdelivery.addressables/blob/master/Runtime/ResourceHandlers/AssetPackAsyncAssetBundleResourceHandler.cs#L9

**Comment by Jason-Zy** [comment]
hi，does it surpport <Pack Together By Label>, i have some groups , and every group contains many bundles which are build by label, and each group is a assetpack, something is wrong when i run it on my device:

**Comment by Jason-Zy** [comment]
![image](https://user-images.githubusercontent.com/26757867/129700015-ba8b2b8b-2f44-442e-a69d-dfda16bb4d25.png)
![image](https://user-images.githubusercontent.com/26757867/129700121-c3890f80-fdc0-49db-a3d4-5f5607ba69f9.png)

**Comment by jelte** [comment]
it seems it can't load a bundle "common.bytes"? not sure where this comes from or if this is something new in addressables.
Usually bundles ended on `.bundle` as such https://github.com/jelte/be.khepri.play.assetdelivery.addressables/blob/master/Runtime/ResourceHandlers/AssetPackAssetBundleResourceHandlerBase.cs#L15 doesn't handle that bundle as a AssetPackBundle. 
You could try changing that if statement to allow .bytes files. But I would first figure out where it comes from.
