### ISSUE TITLE
Error when creating config for Adressable groups.

### ISSUE THREAD

**Issue by sunrizes** [jelte/be.khepri.play.assetdelivery.addressables#43]
I added adressable asset bundles to my adressable groups and built them. I get the following error every time I select 'Create config for Adressables Groups':

![Screenshot_4](https://user-images.githubusercontent.com/73702148/151935087-b1147665-a176-493c-8a51-a5165efd363a.png)

I used the 'Default build script' for building adressables.

My adressable groups look like this:

![Screenshot_5](https://user-images.githubusercontent.com/73702148/151935221-0c24515c-9560-4134-a72d-bf7442cb20d1.png)

The asset bundle adressable settings look like this:

![Screenshot_6](https://user-images.githubusercontent.com/73702148/151935299-0d95e2a7-ce1b-4f54-8e56-6235aa21dfd4.png)

My guess is that I'm doing something wrong.

**Comment by a-l-e-x-d-s-9** [comment]
I'm too experienced strange problems sometimes when upgraded packages. 
I'm using Addressables package version 1.18.9 (later version would not work for me), and Google Play Plugins 1.5.0 (1.4.0 used to work fine too.).
Not sure how exactly to fix your problem, but you can try: Build > Clean Build >  All.
Also try to close and reopen Unity, or even restart the whole system.
Maybe it's related to problem with a build path, that's how I defined it on my system and it is working:
![image](https://user-images.githubusercontent.com/6518064/151939918-398612ab-24f5-4636-967e-481634901418.png)

**Comment by jelte** [comment]
Hey,

This generally happens when you haven't build Addressables or there was an error during building them.

if you have a look to make sure Addressables are actually build in `Library\com.unity.addressables`.

**Comment by sunrizes** [comment]
Looks like Addressables are actually being built by the looks of it.

![Screenshot_7](https://user-images.githubusercontent.com/73702148/151947453-2c360913-54a0-4f6c-9e0c-8c7562fd2433.png)

The console is not reporting any issues while building them. However when I try to create the config, the console gives me this message:



[AssetPackBuilder.CreateAssetPacks] path=
UnityEngine.Debug:LogFormat(String, Object[])
Khepri.PlayAssetDelivery.Editor.AssetPackBuilder:CreateAssetPacks(TextureCompressionFormat, String) (at Assets/AdressablesAssetDelivery/Editor/AssetPackBuilder.cs:41)
Khepri.PlayAssetDelivery.Editor.AssetPackBuilderMenu:CreateConfig() (at Assets/AdressablesAssetDelivery/Editor/AssetPackBuilderMenu.cs:14)

![Screenshot_9](https://user-images.githubusercontent.com/73702148/151947655-7769cac2-4623-47d5-b715-c1bb1c103370.png)

**Comment by jelte** [comment]
hm, can you check your Addressables Active Profile that there is a variable `Local.BuildPath` ?

**Comment by sunrizes** [comment]
Ok this is my current active profile.

![Screenshot_10](https://user-images.githubusercontent.com/73702148/151950715-72f16016-e7c6-455a-8678-81257e615b1a.png)

**Comment by jelte** [comment]
Yeah, I guess that's the problem.
the code uses `AddressableAssetSettings.kLocalBuildPath`  to determine where the bundles are located, which has the value `Local.BuildPath`

Probably this was changed in a later version of Addressables then when you first created the profile (is my best guess)

You could add the variable `Local.BuildPath` with the same value as your `LocalBuildPath`.

**Comment by sunrizes** [comment]
That looks like it solved the problem. Thanks a lot!
