### ISSUE TITLE
AssetModuleException, Blcack screen

### ISSUE THREAD

**Issue by Youngchangoon** [jelte/be.khepri.play.assetdelivery.addressables#49]
Unity Version: 2020.3.20f
Google Unity Plugin Version: 1.7.0
play.assetDelivery.addressables Version: 1.0.0

Link the plugin, it will be uploaded to Google Play well even if it exceeds 150mb.
However, when I run the game, I get the following error.
How to solve this error?

```
2022-04-26 12:33:08.881 8543-8840/? E/PlayCore: UID: [10297]  PID: [8543] AssetPackServiceImpl : onError(-2)
2022-04-26 12:33:08.890 1266-8909/? E/Finsky: [43160] fla.accept(75): Request execution failed with error code: -2
    com.google.android.finsky.assetmoduleserviceutils.AssetModuleException: Request to PGS failed because all packs are unavailable.
        at eqi.Xv(PG:54)
        at euq.l(PG:7)
        at duy.run(PG:5)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:237)
        at android.app.ActivityThread.main(ActivityThread.java:8167)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
```

**Comment by jelte** [comment]
Hey,
This seems to be an issue on Google's side of things or unity's, rather than the plugin. A quick search resulted in the following: 
https://github.com/google/play-unity-plugins/issues/127

Could you try that?

**Comment by Youngchangoon** [comment]
Thanks for referencing the link and replying.

I already tried this solution, and not working for me.

And I'll try to add issue on play-unity-plugins. Thanks!

**Comment by a-l-e-x-d-s-9** [comment]
From my experience there some compatibility issue with Unity Addressable package after 1.18.9 version. While 1.18.9 is working fine.
I can confirm the software versions that worked for me:
Unity Version: 2020.3.15f-2020.3.33f. (Unity 2021 has unrelated problem, so I haven't tested with it.)
Unity Addressable package: 1.18.9. (Later versions don't work.)
Google Play Assetdelivery: 1.5.0, 1.6.0. (Haven't tested newer versions.)

I would suggest to try Unity Addressable package 1.18.9.

**Comment by Youngchangoon** [comment]
I tried changing the version as per your advice, but the same error repeats...

**Comment by jelte** [comment]
Could you check your build log for any errors that may be silently ignored?

Just to confirm:
- are you using a custom build script/function?
- you have build addressables before building the app? ( Or your buildscript does this)

**Comment by Youngchangoon** [comment]
Thanks to replying :D

When I build addressable, the above warning appears. but it was okay for a long time.
and I always build addressables before building the app
```
Sprite box_title matches more than one built-in atlases. Default to use the first available atlas.
```

Also, I used automation build in the past, but I turned it off for a while to apply PAD.
( I think that resigning after the build for game security might be a problem. )

```
cmd=`jarsigner -tsa http://timestamp.digicert.com -verbose -sigalg SHA256withRSA -digestalg SHA-256 -keystore ./Android/AndroidKey.keystore ./Android/${fileName}.aab alisename`
```

and I'm continuing to find about this issue

**Comment by jelte** [comment]
The first one shouldn't be a problem.
The second one is, the ${filename} should be replaced I think. Don't have access to my computer till later in the week, so can't really check.
When you upload the aab to the playstore, does it not give any errors there that the aab isn't signed properly?

**Comment by Youngchangoon** [comment]
I do not know the exact cause, but when I received the PAD plugin supported by [Unity](https://github.com/Unity-Technologies/Addressables-Sample) and applied it while watching the sample, it worked well.

Thanks for your help in resolving the problem.
