### ISSUE TITLE
Error upon adding package

### ISSUE THREAD

**Issue by SorenMuller** [jelte/be.khepri.play.assetdelivery.addressables#51]
When I add the  package i get the following error:

Library\PackageCache\be.khepri.play.assetdelivery.addressables@8ec2fd15b7c515d0c59c90e4b31c57ad6fafc9af\Runtime\ResourceHandlers\WebRequestAssetBundleResourceHandlerBase.cs(41,42): error CS0103: The name 'options' does not exist in the current context

I'm using Unity 2018.4,12f1 and adressables version 1.8.5..

**Comment by jelte** [comment]
This should be resolved in 1.0.2.
