### ISSUE TITLE
Create config for Addressables Groups returns error

### ISSUE THREAD

**Issue by aholla** [jelte/be.khepri.play.assetdelivery.addressables#61]
<img width="243" alt="image" src="https://user-images.githubusercontent.com/1239908/184457705-f03e91fd-0278-4a0c-b232-79f2e86d662d.png">

**Comment by Karottenrambo** [comment]
I had the same issue here:
https://github.com/jelte/be.khepri.play.assetdelivery.addressables/discussions/57

appearently this package is not compatible with the addressable versions 1.19 and higher.

In my project I also had building issues, even with the older versions, I delayed implementing them and will revisit if an updated version is released.

**Comment by jelte** [comment]
There is an issue with 1.19 and unity 2021, as from that version Addressables no longer copies to StreamingAssets during the build process.

**Comment by jelte** [comment]
If you use 1.0.1, this should be resolved.
