### ISSUE TITLE
All asset bundles also in base_assets when using Unity 2021

### ISSUE THREAD

**Issue by szeleneyr** [jelte/be.khepri.play.assetdelivery.addressables#62]
We make use of this plugin for quite a while now which always worked flawlessly since Unity 2019. But after upgrading to Unity 2021.3.5f1 the final AAB is almost double size, after investigating it looks like all assets bundles are also part of base_asset (base_assets/assets/aa has all asset bundles too, which was not the case in earlier versions).

Is this maybe a known issue already? Does anyone have a hint where to look at? (maybe Unity 2021 is building the addressables again when building the player?)

We are using Addressables 1.19.19 and play-asset-delivery 1.7.0 (worked fine with Unity 2020)

**Comment by jelte** [comment]
Yes, there is an issue with 2021 and addressables 1.19+, as in the combination of those, Addressables no longer copies bundles to StreamingAssets. 

Not sure how to fix it yet, but I got some time off in 2 weeks, at which point I'll be taking a look at this.

**Comment by szeleneyr** [comment]
Thanks you for the update. I mean, they work fine, they build correctly, upload correctly and can be loaded/addressed without any issue. The problem is "just" that the base/base_assets bundle also contains all the asset bundles. 

If you take a look at the delivery section in play console you will see that the base_assets bundle is the size of base.bundle and all other asset bundles.

While building, I saw that at one point in the process the com.unity.addressables/assets/android folder is cleaned while building the player with Unity 2020, but it is not cleaned when building with 2021, maybe thats the reason?

Anyway, thanks for taking a look at this, let me know if you need someone to debug and test early, I will be around!

**Comment by szeleneyr** [comment]
Did you have any chance looking at this issue already? Any way I can be of help here?

**Comment by szeleneyr** [comment]
We started to look for alternative instead of this plugins, appears its dead?

**Comment by jelte** [comment]
Sorry, I've been extremely busy with work lately and had little time. 

I had a quick look, but I haven't had time to verify the fix.

so I thought it is as simple as changing:

PlayAssetPackBundlesPreprocessor.cs line 22 to use the BuildPath instead of PlayerBuildDataPath
```
var bundles = AssetPackBuilder.GetBundles(Addressables.BuildPath, SearchOption.AllDirectories);
```

But Unity changed how android is being build, and adds things to a manifest list, which isn't accessable, so I need to hack around that..., thank you Unity...

**Comment by jelte** [comment]
Ok think I resolved it, a less hacky way then what you suggested.

Basically by removing the bundle slightly earlier in the process than in Unity 2020.

I've created a new release 1.0.1.

**Comment by szeleneyr** [comment]
Is it possible that AssetPackBuilder is not uptodate? looks like ClearConfig() and GetBundles() modifications are missing?

**Comment by szeleneyr** [comment]
Unfortunately your fix didn't solve the issue, actually got worse
- I have still all addressables asset bundles duplicated in base/assets/aa or base_assets/assets/aa
- The base module (if SplitBaseModule is disabled) doesn't contain the ManageData folder anymore which makes the app crash

**Comment by lvgrecords** [comment]
> Unfortunately your fix didn't solve the issue, actually got worse
> 
> * I have still all addressables asset bundles duplicated in base/assets/aa or base_assets/assets/aa
> * The base module (if SplitBaseModule is disabled) doesn't contain the ManageData folder anymore which makes the app crash

same for me :(
