### ISSUE TITLE
Error with new 1.0.2 version, when using Google>Create config for Addressables Groups

### ISSUE THREAD

**Issue by a-l-e-x-d-s-9** [jelte/be.khepri.play.assetdelivery.addressables#63]
I have been using assetdelivery.addressables 1.0.0, Unity Addressables 1.18.9, Unity 2020.3.39f1, google play-unity-plugins 1.7.
Today I've upgrade to assetdelivery.addressables 1.0.2 version, Unity Addressables 1.19.19, Unity 2021.3.11f1.
Then I did:
1. Addressables Groups>Clean Build>All
2. Addressables Groups>New Build>Default Build Script
3. Google > Create config for Addressables Groups 
Got an error: Unable to create AssetPack config. Make sure Addressables asset bundles have been build!
In the log message: "[AssetPackBuilder.CreateAssetPacks] path=" 
Do I need to configure this folder somewhere?

**Comment by jelte** [comment]
Normally it should fall back to the `Local.BuildPath` in your active addressables profile. Could it be that variable isn't defined?

(I'll add an additional fallback just in case)

**Comment by a-l-e-x-d-s-9** [comment]
That's what defined in my AddressableAssetSettings:
![image](https://user-images.githubusercontent.com/6518064/194018486-94a82e53-5ab5-4a36-a6e0-9f15af176328.png)

And for asset group: 
![image](https://user-images.githubusercontent.com/6518064/194019380-ae2d63ae-200b-4744-a1b7-d5b9436ecdb9.png)

Is it ok or should it be something else?

**Comment by jelte** [comment]
Yeah, I think unity renamed LocalBuildPath to Local.BuildPath, so if you are having an older config it would find it's default local build path anymore :(

**Comment by jelte** [comment]
if you get 1.0.3 it should fallback to the Addressable.BuildPath, if Local.BuildPath param isn't found.

**Comment by a-l-e-x-d-s-9** [comment]
Ok, looks that it solved it.
Thanks!
