### ISSUE TITLE
Unity 2022.3 bug

### ISSUE THREAD

**Issue by TrueRaider** [jelte/be.khepri.play.assetdelivery.addressables#74]
Who working with unity 2022, please help! After upgrade from 2021 to 2022, PAD not working, Release note says: **The default minimum version of Google Play Library for Asset Delivery has been upgraded to 2.0.0 with Unity built-in support.** [https://unity.com/releases/editor/whats-new/2022.2.12](url) 
After upgrade GP plugins android build running without crashes, but can't load any bundle with error:
Unable to open archive file: jar:file:///data/app/~~tIaTEm6kpHrV6Wod3ljE_A==/YOy0S8nqV6fDWuwkJKqPCQ==/base.apk!/assets/aa/Android/duplicateassetisolation_assets_all_974cb341ec16d02852979460087b03ef.bundle
Looks like, client tried to download bundle from base_module. But this group located in asset pack.

**Comment by k119-55524** [comment]
Exactly the same problem.

**Comment by firdiar-mita** [comment]
i think this is the solution
https://github.com/jelte/be.khepri.play.assetdelivery.addressables/issues/75
