### ISSUE TITLE
Retrive assets from installtime pack

### ISSUE THREAD

**Issue by aleksanderwlodarczyk** [jelte/be.khepri.play.assetdelivery.addressables#9]
I followed the instruction in README, everything went ok, aab has included the pack, but how do I 'unload it' in build?

EDIT: When i try to load it with `Addressables.LoadAssetAsync()` I got this exception in logcat

```
11-02 23:04:14.101 20492 20533 E Unity   : Exception encountered in operation Dependencies [base6_assets_all_ecfca279f78dbfc7b79f6c6b455f..., defaultlocalgroup_unitybuiltinshaders_3882323...], status=Failed, result=System.Collections.Generic.List`1[UnityEngine.R
esourceManagement.AsyncOperations.AsyncOperationHandle] : Object reference not set to an instance of an object.
11-02 23:04:14.101 20492 20533 E Unity   : UnityEngine.AddressableAssets.AddressablesImpl:LogException(AsyncOperationHandle, Exception)
```

**Comment by jelte** [comment]
could you explain more what you mean with "unload it", 
install time Asset packs are installed/updated by android / google play store automatically. There shouldn't be a need to "unload it".
Bundles are then loaded from the asset packs and unloaded by addressables. 

if you want to debug more of what is going on in the background you can add `DEBUG_PLAYASSETDELIVERY` to "Scripting Define Symbols" in the "Player Settings" before you create a new AAB.

**Comment by jelte** [comment]
Hey, sorry I missed your edit, can you tell me which version of addressables you are using?

**Comment by a-l-e-x-d-s-9** [comment]
I think that this is the same problem I've just had.
You probably didn't configure "Default Local Group" properly. 
More info in #27.
